### ISSUE TITLE
Add `.multiple()`

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/random-item#3]
Allow taking multiple random items like `_.sampleSize()`:

```js
const randomItem = require('random-item');

randomItem.multiple([1, 2, 3, 4, 5], 2);
//=> [1, 4]
```

Not entirely sure on what the function name should be; maybe `.some()`.

// @sindresorhus

**Comment by sindresorhus** [comment]
Sounds good. I prefer the `multiple` naming.
